[package]
name = "pirate_jam_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy-inspector-egui = "0.22.1"
bevy_rapier2d = "0.23.0"
bevy_rapier3d = "0.23.0"
